version: "3"

services:
  wisper-api:
    image: danubise/wisper:latest
    container_name: wisper
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./models:/opt/wisper/models
      - ./uploads:/opt/wisper/uploads
